name: 'required-versions-action'
description: 'grab required versions from package.json, put them in a changelog'
inputs:
  version:
    description: 'The version you are listing under in the Release Notes.'
    required: true
  changelog:
    description: 'The changelog to add the information to.'
    required: false
    default: 'changelog.md'
  githubUser:
    description: 'The user that the repositories with required versions belong to'
    required: true
runs:
  using: "composite"
  steps:
    - name: required versions
      id: required
      run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        version: ${{ inputs.version }}
        githubUser: ${{ inputs.github.user }}
        changelog: ${{ inputs.changelog }}
    - name: lint
      uses: avto-dev/markdown-lint@v1
      with:
        args: './${{ inputs.changelog }} --fix'
